### ISSUE TITLE
it's not working.

### ISSUE THREAD

**Issue by rbauer1186** [sanukin39/UniAndroidPermission#8]
Hi. I tried to use your plugin but it's not working. The dialog isn't showed. when i builded a emty app with the plugin, the app goes out after calling request permission function. Can your help me fix this issue?

**Comment by sanukin39** [comment]
Hi rbauer1186,

Thank you for the report. I'll try to fix it.
So, would you tell me more information about your environment?

・Unity version
・Permission you want to permit
・your android device name
・your android device OS version

tanks,

**Comment by rbauer1186** [comment]
Hi. Thank you for helping me. I  use Unity version 5.3.5f1. i request permission WRITE_EXTERNAL_STORAGE. 
i use a huawei phone with android 6.0.

**Comment by rbauer1186** [comment]
my phone is rooted. maybe it causes the error.

**Comment by astechnolabs-fullstack** [comment]
I am facing same error, I have new phone not rooted

Android **OS 13**
Google **Pixel 6A**
permission: **WRITE_EXTERNAL_STORAGE**
unity : **2020.3.26f**

Same error, please help me to figureout

```
AndroidJavaException: java.lang.ClassNotFoundException: net.sanukin.PermissionManager
	java.lang.ClassNotFoundException: net.sanukin.PermissionManager
		at java.lang.Class.classForName(Native Method)
		at java.lang.Class.forName(Class.java:536)
		at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
		at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
		at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
		at android.os.Handler.dispatchMessage(Handler.java:103)
		at android.os.Looper.loopOnce(Looper.java:232)
		at android.os.Looper.loop(Looper.java:317)
		at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
	Caused by: java.lang.ClassNotFoundException: net.sanukin.PermissionManager
		at java.lang.Class.classForName(Native Method) 
		at java.lang.Class.forName(Class.java:536) 
		at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
		at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0) 
		at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95) 
		at android.os.Handler.dispatchMessage(Handler.java:103) 
		at android.os.Looper.loopOnce(Looper.java:232) 
		at android.os.Looper.loop(Looper.java:317) 
		at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) 
		at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
		at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
		at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String clas
```
